### ISSUE TITLE
 Cannot find module 'color-contrast-checker'

### ISSUE THREAD

**Issue by nasreenshaik** [bbc/color-contrast-checker#2]
I am getting  "Error: Cannot find module 'color-contrast-checker'" when using the given code. Please advise.

Thanks

**Comment by timmydd** [comment]
I'm getting this issue too....

**Comment by Qambar** [comment]
Can you provide more information on what commands you were running when you got that error message ?

**Comment by nasreenshaik** [comment]
This issue is seen in Run Kit as well. I just opened Run Kit and clicked RUN. Same thing with my code. Kindly check.

**Comment by Qambar** [comment]
what is "Run Kit"? and 

isn't it a problem with that Run Kit that it is not downloading the library as per the error message it suggests that it has not downloaded the package which it is referring to.

**Comment by nasreenshaik** [comment]
Below is the error i get even after installing using "npm install color-contrast-checker"


Unhandled rejection Error: Cannot find module 'color-contrast-checker'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\SLite\stepdefinitions\flight_results_steps.ts:6:28
)
    at Module._compile (module.js:570:32)
    at Module.m._compile (C:\SLite\node_modules\ts-node\src\index.ts:392:23)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\SLite\node_mo
dules\ts-node\src\index.ts:395:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at C:\SLite\node_modules\cucumber\lib\cli\index.js:135:16
    at Array.forEach (native)

[11:27:05] E/launcher - BUG: launcher exited with 1 tasks remaining
npm ERR! Test failed.  See above for more details.



Code i used:
var ColorContrastChecker = require('color-contrast-checker');

Then(/^Color Contrast Checker$/, async () => {

        var ccc = new ColorContrastChecker();

        var color1 = "#FFFFFF";
        var color2 = "#000000";

        if (ccc.isLevelAA(color1, color2, 14)) {
            alert("Valid Level AA");
        } else {
            alert("Invalid Contrast");
        }
    })

**Comment by Qambar** [comment]
@nasreenshaik : Try using the V1.3.0. There was a problem with how amdefine was used. It was working with requirejs but not with node. So i have made some code changes to fix that compatibility issue.

**Comment by nasreenshaik** [comment]
Perfect!! Thank you so much its working fine now. Is  there a way were we can send the whole webpage url and get the output. writing for each component this way is very difficult. Thanks again for this fix.

**Comment by Qambar** [comment]
okay, i am going to close this issue then, i am opening another one with your feature request, we can discuss that over there. Here is the link : https://github.com/Qambar/color-contrast-checker/issues/3
